# SPDX-License-Identifier: AGPL-3.0-or-later
# Kitchen Samplers. Third-party code and licenses: NOTICE.md

"""Regenerate lib_kitchen/canon/ from reForge and Neo source.

    python tools/vendor.py /path/to/reForge /path/to/Forge-Classic-Neo

Only host plumbing is rewritten (model sampling, CONST, post-CFG, opts, randn_like).
Where both WebUIs have a function, Neo's copy is taken.
"""

from __future__ import annotations

import ast
import pathlib
import re
import subprocess
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "lib_kitchen" / "canon"

COMMON = ["to_d", "append_dims", "get_ancestral_step", "default_noise_sampler", "ei_h_phi_1",
          "ei_h_phi_2", "sigma_to_half_log_snr", "half_log_snr_to_sigma",
          "offset_first_sigma_for_snr", "BatchedBrownianTree", "BrownianTreeNoiseSampler"]

FROM_NEO = ["sample_euler_ancestral_RF", "sample_euler_ancestral_cfg_pp", "sample_euler_cfg_pp",
            "sample_dpmpp_2m_cfg_pp", "res_multistep", "sample_res_multistep", "sample_er_sde"]

FROM_REFORGE = ["DDPMSampler_step", "generic_step_sampler", "sample_ddpm", "sample_heunpp2",
                "sample_ipndm", "sample_ipndm_v", "sample_deis",
                "sample_dpmpp_2s_ancestral_cfg_pp", "sample_dpmpp_sde_cfg_pp",
                "sample_dpmpp_3m_sde_cfg_pp",
                "sample_res_multistep_cfg_pp", "sample_res_multistep_ancestral",
                "sample_res_multistep_ancestral_cfg_pp",
                "sample_gradient_estimation", "sample_gradient_estimation_cfg_pp",
                "sample_seeds_2", "sample_seeds_3", "sample_sa_solver", "sample_sa_solver_pece"]


def git_head(root: pathlib.Path) -> str:
    try:
        return subprocess.check_output(["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def reforge_defaults(root: pathlib.Path) -> dict:
    src = (root / "modules/shared_options.py").read_text()
    out = {}
    for key, val in re.findall(r'"([a-zA-Z0-9_]+)":\s*OptionInfo\(\s*([^,\n]+?),', src):
        try:
            out[key] = eval(val.strip(), {"__builtins__": {}}, {})
        except Exception:
            out[key] = val.strip().strip("\"'")
    return out


def top_level(src: str) -> dict[str, str]:
    """name -> source of the LAST top-level def/class of that name (later wins,
    as it does when Python imports the module)."""
    tree = ast.parse(src)
    out = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            seg = ast.get_source_segment(src, node)
            deco = "".join("@" + ast.get_source_segment(src, d) + "\n" for d in node.decorator_list)
            out[node.name] = deco + seg
    return out


POST_CFG = re.compile(
    r'extra_args\["model_options"\]\s*=\s*(?:ldm_patched\.modules\.model_patcher\.)?'
    r'set_model_options_post_cfg_function\(\s*model_options\s*,\s*post_cfg_function\s*,'
    r'\s*disable_cfg1_optimization\s*=\s*True\s*\)')


def rewrite(code: str, defaults: dict) -> str:
    code = re.sub(r'model\.inner_model\.model_patcher\.get_model_object\(\s*[\'"]model_sampling[\'"]\s*\)',
                  "_host.model_sampling(model)", code)
    code = code.replace("model.inner_model.inner_model.model_sampling", "_host.model_sampling(model)")
    code = code.replace("model.inner_model.predictor", "_host.model_sampling(model)")
    code = re.sub(r"isinstance\((\w+),\s*ldm_patched\.modules\.model_sampling\.CONST\)", r"_host.is_const(\1)", code)
    code = re.sub(r"isinstance\((\w+),\s*CONST\)", r"_host.is_const(\1)", code)
    code = re.sub(r"\b_is_const\(", "_host.is_const(", code)
    if POST_CFG.search(code):
        code = POST_CFG.sub("extra_args = _host.with_post_cfg(model, extra_args, post_cfg_function)", code)
        if not code.lstrip().startswith("@_host.scoped"):
            code = "@_host.scoped\n" + code

    def opt(m):
        key = m.group(1)
        if key not in defaults:
            raise SystemExit(f"option {key} has no reForge default")
        return f"_host.opt({key!r}, {defaults[key]!r})"
    code = re.sub(r"\bmodules\.shared\.opts\.([a-zA-Z0-9_]+)", opt, code)
    code = re.sub(r"(?<![\w.])opts\.([a-zA-Z0-9_]+)", opt, code)
    code = code.replace("torch.randn_like(", "_host.randn_like(")
    return code


HEADER = '''# SPDX-License-Identifier: AGPL-3.0-or-later (as the source WebUI). See NOTICE.md.
"""{what}

GENERATED by tools/vendor.py - do not edit by hand; edit the generator.

Source: {source} at commit {commit}.
Licensed as the source is (see LICENSE and NOTICE.md). The only changes are the
host-plumbing rewrites listed in tools/vendor.py.
"""
# ruff: noqa
'''


def emit(path, what, source, commit, imports, bodies):
    text = HEADER.format(what=what, source=source, commit=commit) + imports + "\n\n" + "\n\n\n".join(bodies) + "\n"
    ast.parse(text)
    path.write_text(text)
    print(f"wrote {path.relative_to(OUT.parent.parent)}  ({len(text.splitlines())} lines)")


def main(reforge_root, neo_root):
    reforge_root, neo_root = pathlib.Path(reforge_root), pathlib.Path(neo_root)
    OUT.mkdir(parents=True, exist_ok=True)
    defaults = reforge_defaults(reforge_root)
    rf_commit, neo_commit = git_head(reforge_root), git_head(neo_root)

    rf_src = (reforge_root / "ldm_patched/k_diffusion/sampling.py").read_text()
    neo_src = (neo_root / "modules_forge/packages/k_diffusion/sampling.py").read_text()
    rf, neo = top_level(rf_src), top_level(neo_src)

    (OUT / "__init__.py").write_text('"""Samplers copied from the WebUIs that have them (see tools/vendor.py)."""\n')

    emit(OUT / "common.py", "Helpers shared by the copied samplers (from reForge's k-diffusion).",
         "reForge ldm_patched/k_diffusion/sampling.py", rf_commit,
         "import math\n\nimport torch\n\nfrom lib_kitchen import host as _host",
         [rewrite(rf[n], defaults) for n in COMMON if n != "BatchedBrownianTree" and n != "BrownianTreeNoiseSampler"]
         + ["def _torchsde():\n    import torchsde\n    return torchsde"]
         + [rewrite(rf[n], defaults).replace("torchsde.BrownianTree", "_torchsde().BrownianTree")
            for n in ("BatchedBrownianTree", "BrownianTreeNoiseSampler")])

    common_import = ("import math\nfrom functools import partial\n\nimport torch\nfrom tqdm.auto import trange\n\n"
                     "from lib_kitchen import host as _host\nfrom lib_kitchen.canon.common import *  # noqa: F401,F403\n"
                     "from lib_kitchen.canon.common import (to_d, append_dims, get_ancestral_step, default_noise_sampler,\n"
                     "    ei_h_phi_1, ei_h_phi_2, sigma_to_half_log_snr, half_log_snr_to_sigma,\n"
                     "    offset_first_sigma_for_snr, BrownianTreeNoiseSampler)")

    emit(OUT / "from_neo.py", "Samplers Forge Classic (Neo) has and other WebUIs lack.",
         "Forge Classic (Neo) modules_forge/packages/k_diffusion/sampling.py", neo_commit,
         common_import, [rewrite(neo[n], defaults) for n in FROM_NEO])

    emit(OUT / "from_reforge.py", "Samplers reForge has and other WebUIs lack.",
         "reForge ldm_patched/k_diffusion/sampling.py", rf_commit,
         common_import + "\nfrom lib_kitchen.canon import deis, sa_solver\nfrom lib_kitchen.canon.from_neo import res_multistep",
         [rewrite(rf[n], defaults) for n in FROM_REFORGE])

    for mod in ("deis", "sa_solver"):
        src = (reforge_root / f"ldm_patched/k_diffusion/{mod}.py").read_text()
        (OUT / f"{mod}.py").write_text(
            HEADER.format(what=f"reForge's k-diffusion {mod} helpers, unchanged.",
                          source=f"reForge ldm_patched/k_diffusion/{mod}.py", commit=rf_commit) + src)
        print(f"wrote lib_kitchen/canon/{mod}.py")

    smea_src = (reforge_root / "modules/sd_samplers_kdiffusion_smea.py").read_text()
    smea = top_level(smea_src)
    names = ["Rescaler", "dy_sampling_step", "sample_euler_dy", "smea_sampling_step",
             "sample_euler_smea_dy", "sample_euler_negative", "sample_euler_dy_negative"]
    bodies = [rewrite(smea[n], defaults).replace("sampling.to_d(", "to_d(") for n in names]
    emit(OUT / "smea.py", "reForge's Euler Dy / SMEA Dy / Negative samplers (Koishi-Star's originals).",
         "reForge modules/sd_samplers_kdiffusion_smea.py", rf_commit,
         "import torch\nfrom tqdm.auto import trange\n\nfrom lib_kitchen import host as _host\n"
         "from lib_kitchen.canon.common import to_d", bodies)


if __name__ == "__main__":
    main(*sys.argv[1:3])
